### ISSUE TITLE
Filter ministry wise and specific dates

### ISSUE THREAD

**Issue by revendrat** [nit-in/pib#25]
Hi Nitin,
Good work in scraping PIB news articles. Possible to scrape ministry wise and filter for specific dates? 
An example: Ministry of Finance from 1 September 2023 to 1 October 2023? It will be a helpful feature. Thank you!

**Comment by nit-in** [comment]
Hey...Sorry for replying late. I have been busy. I have pushed few changes so we can choose dates and ministry also. I will be pushing  more changes for github actions so you can fork the repository and run the workflow for dates and ministry you desire, also you would not need your local pc, you just need to run the workflow manually and download the files

I will also update the READ.ME file for instructions

**Comment by revendrat** [comment]
Thank you so much! Shall wait for updated read.me file to follow the instructions.

**Comment by nit-in** [comment]
You can now fork the repo and 
Go to (You may have add repo secret named PIB)
check the [process](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-secrets-for-your-repository-and-organization-for-github-codespaces#:~:text=Adding%20secrets%20for%20a%20repository,-To%20create%20secrets&text=Under%20your%20repository%20name%2C%20click,page%2C%20click%20New%20repository%20secret.)


```
Actions > Select "PIB_INDIA_MINISTRY" > Run workflow
and Select appropriate options and run the workflow
```
![IMG_20231106_101656](https://github.com/nit-in/pib/assets/8947263/38355326-e425-4cd0-9d93-156d39abded5)

To run locally
```
source .env
pib_min start_date end_date ministry_code
```

**For ministry code check ministries.txt file for desired ministry**

**Comment by revendrat** [comment]
Thank you so much!

**Comment by nit-in** [comment]
you may have trouble with github tokens when you are running it after forking it
click on profile icon > Settings > Developer settings > Personal access tokens > generate new token(classic)
Name it, no expiration
in scopes > select repo, workflow, write and delete packages, 
then generate and copy it



 then go to pib repo
Settings > Secrets and variables > Actions
here new repository secret
in name enter PIB ( all in caps)
and in secret > paste the token you copied

**Comment by revendrat** [comment]
Thank you so much! This is amazing and it runs well on Github workflow. 
I followed the instructions and running it on the local. Facing this error. Any suggestions on how to resolve it? Thank you!

```
revendrat pib % pib_min 2023-11-01 2023-11-18 8
date: invalid argument '--date' for -I
date: invalid argument '--date' for -I

Starting date   :

End date        :

Selected ministry is    :

Ministry of Education

Enter correct set of arguments (date date ministry_code)
 Enter Date in format of YYYY-MM-DD
```

**Comment by nit-in** [comment]
@revendrat I have pushed a commit, that might fix the issue when running locally

I would recommend (for now) using the github workflow as it will save you time and also when running locally there is a issue with chromedriver versioning. Due to lack of time I am not able to work on it.

And whenever using the github actions workflow try not to keep the initial and final dates too far like 2-3 months are fine, more than that it may fail as github action will run for 6hrs on one go.

**Comment by revendrat** [comment]
You are awesome! Thank you so much again! Shall follow your advice of keeping it short to less than 2-3 months.
May I have your email id, to exchange some notes?

**Comment by nit-in** [comment]
closing this for now..
