### ISSUE TITLE
PIB Archives [Enhancement Request]

### ISSUE THREAD

**Issue by revendrat** [nit-in/pib#30]
Possible to access ministry wise article between two dates from these tow PIB Archives website: 
From 2004 to 2017: https://archive.pib.gov.in/archive2/erelease.aspx
Thank you!

**Comment by nit-in** [comment]
started working on it.... you can check the progress by checking the archives branch

**Comment by nit-in** [comment]
I have pushed the changes and should be working now
closing this for now. if you face any issues you can reopen it
